#!name=Ulysses
#!desc=Ulysses
#!homepage=https://yfamily.vercel.app
#!author=J

[MITM]
hostname = %APPEND% sk.ulysses.app
[Script]
白描=type=http-response,pattern=^https?:\/\/baimiao\.uzero\.cn\/api\/v\d\.user\/appLaunchWithUser$,requires-body=1,script-path=https://raw.githubusercontent.com/iEwha/Profiles/master/Script/baimiao.js

Ulysses=http-request,pattern=^https:\/\/sk\.ulysses\.app\/api\/v1\/user_offers$,script-path=https://raw.githubusercontent.com/langkhach270389/Scripting/master/cleancacheulysses.js

Ulysses=http-response,pattern=^https:\/\/sk\.ulysses\.app\/api\/v1\/itunes_receipt_verify$,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/langkhach270389/Scripting/master/ulysses.js

